/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista entregas
         * @description Todas as entregas, das mais novas para as mais antigas. Filtros opcionais.
         */
        get: operations["listDeliveries"];
        put?: never;
        /**
         * Registra uma entrega
         * @description Grava a entrega como `pending` e agenda a notificação de chegada.
         *     Sem `resident_id`, com um morador inexistente ou de outro apartamento, a entrega vai para o morador "Outro".
         */
        post: operations["registerDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/deliveries/{delivery_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Marca a entrega como retirada
         * @description Agenda a notificação de retirada. Idempotente.
         */
        delete: operations["pickUpDelivery"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/apartments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os apartamentos com moradores
         * @description Sem repetição, em ordem natural (2, 63, 101, 101A). O morador "Outro" não conta.
         */
        get: operations["listApartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/residents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista moradores de um apartamento ou de um telefone
         * @description Informe `apartment` ou `phone`, não os dois. Inclui o morador "Outro" do apartamento.
         */
        get: operations["listResidents"];
        put?: never;
        /**
         * Cadastra um morador
         * @description O primeiro morador do apartamento vira `resident-primary`. Só `admin`.
         */
        post: operations["createResident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/residents/{resident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove um morador
         * @description Remoção lógica. Se era o principal, o mais antigo do apartamento é promovido. Só `admin`.
         */
        delete: operations["deleteResident"];
        options?: never;
        head?: never;
        /**
         * Atualiza um morador
         * @description Atualização parcial; campo vazio ou omitido não muda. Só `admin`.
         */
        patch: operations["updateResident"];
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cria um usuário (admin ou porteiro)
         * @description A senha vai direto para o Firebase Auth; a API não guarda. Só `admin`.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/pubsub/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push do Pub/Sub (uso interno)
         * @description Recebe o `NotifyDeliveryCommand` pela push subscription. Não é para o front.
         *     Em produção exige o token OIDC assinado pela service account do push.
         */
        post: operations["receivePubSubPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        /**
         * @description `pending`: aguardando retirada; `deleted`: retirada.
         * @enum {string}
         */
        DeliveryStatus: "pending" | "deleted";
        Delivery: {
            delivery_id: string;
            apartment: string;
            resident_id: string;
            /** @description Nome do destinatário. Vem só na listagem. */
            resident_name?: string;
            package_type: string;
            urgency: string;
            status: components["schemas"]["DeliveryStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /**
             * Format: date-time
             * @description Só em entregas retiradas.
             */
            deleted_at?: string;
        };
        RegisterDeliveryRequest: {
            apartment: string;
            resident_id?: string;
            package_type?: string;
            urgency?: string;
        };
        /** @enum {string} */
        ResidentType: "resident-primary" | "resident-secondary" | "other";
        /** @enum {string} */
        ResidentStatus: "created" | "deleted";
        Resident: {
            resident_id: string;
            name: string;
            apartment: string;
            phone: string;
            type: components["schemas"]["ResidentType"];
            status: components["schemas"]["ResidentStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateResidentRequest: {
            name: string;
            apartment: string;
            /** @description Sem código do país, o `NOTIFIER_DEFAULT_COUNTRY_CODE` é adicionado. */
            phone: string;
        };
        /** @description Pelo menos um campo. */
        UpdateResidentRequest: {
            name?: string;
            apartment?: string;
            phone?: string;
        };
        /** @enum {string} */
        Role: "admin" | "doorman";
        User: {
            user_id: string;
            /** Format: email */
            email: string;
            name: string;
            role: components["schemas"]["Role"];
        };
        CreateUserRequest: {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            role: components["schemas"]["Role"];
        };
        PubSubPush: {
            message: {
                /**
                 * Format: byte
                 * @description NotifyDeliveryCommand em JSON, codificado em base64.
                 */
                data?: string;
                attributes?: {
                    [key: string]: string;
                };
                messageId?: string;
            };
            subscription?: string;
            deliveryAttempt?: number;
        };
    };
    responses: {
        /** @description Requisição inválida (JSON, campo obrigatório ou valor inválido). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "apartment is required"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Sem token, token inválido ou expirado. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "unauthenticated"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description O papel do usuário não pode usar a rota. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "forbidden"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Não encontrado. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description O morador "Outro" não pode ser alterado nem removido. */
        OtherResidentReadOnly: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Erro inesperado. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "internal server error"
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        DeliveryID: string;
        ResidentID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API no ar. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDeliveries: {
        parameters: {
            query?: {
                /** @example 101 */
                apartment?: string;
                status?: components["schemas"]["DeliveryStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de entregas. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    registerDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeliveryRequest"];
            };
        };
        responses: {
            /** @description Entrega registrada. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Delivery"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description O apartamento não tem nenhum morador cadastrado. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    pickUpDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                delivery_id: components["parameters"]["DeliveryID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retirada. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    listApartments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Apartamentos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    listResidents: {
        parameters: {
            query?: {
                apartment?: string;
                phone?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Moradores ativos. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resident"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    createResident: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResidentRequest"];
            };
        };
        responses: {
            /** @description Morador cadastrado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resident"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteResident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resident_id: components["parameters"]["ResidentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removido. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OtherResidentReadOnly"];
            500: components["responses"]["InternalError"];
        };
    };
    updateResident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resident_id: components["parameters"]["ResidentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResidentRequest"];
            };
        };
        responses: {
            /** @description Morador atualizado. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resident"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["OtherResidentReadOnly"];
            500: components["responses"]["InternalError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Usuário criado. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description Já existe um usuário com esse e-mail. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    receivePubSubPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PubSubPush"];
            };
        };
        responses: {
            /** @description Mensagem processada (ack), ou tipo de evento ignorado. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Mensagem malformada; vai para o dead-letter depois das tentativas. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token do push ausente ou inválido. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falha ao notificar; o Pub/Sub tenta de novo. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
